"""home grounds

Revision ID: 74b067bae3eb
Revises: 013f58ab23ce
Create Date: 2026-10-03 16:28:37.498732
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "74b067bae3eb"
down_revision: str | None = "013f58ab23ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("club_teams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("home_ground", sa.String(length=200), nullable=True))

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("home_ground", sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_column("home_ground")

    with op.batch_alter_table("club_teams", schema=None) as batch_op:
        batch_op.drop_column("home_ground")

    # ### end Alembic commands ###
