"""ground geocode cache

Revision ID: 39581085fe8b
Revises: 74b067bae3eb
Create Date: 2026-10-03 17:41:24.731325
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "39581085fe8b"
down_revision: str | None = "74b067bae3eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=300), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column(
            "looked_up_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grounds")),
        sa.UniqueConstraint("query", name=op.f("uq_grounds_query")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grounds")
    # ### end Alembic commands ###
