"""initial schema

Revision ID: 34de72645897
Revises:
Create Date: 2026-09-12 22:17:21.513643
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "34de72645897"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "award_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_award_types")),
        sa.UniqueConstraint("code", name=op.f("uq_award_types_code")),
    )
    op.create_table(
        "competitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
        sa.UniqueConstraint("name", name=op.f("uq_competitions_name")),
    )
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("captured_at", sa.DateTime(), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'youtube' AND url IS NOT NULL) OR (kind <> 'youtube' AND storage_key IS NOT NULL)",
            name=op.f("ck_media_source_present"),
        ),
        sa.CheckConstraint("kind IN ('youtube', 'photo', 'file')", name=op.f("ck_media_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("display_name", sa.String(length=50), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("joined_date", sa.Date(), nullable=True),
        sa.Column("left_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=10), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint("code", name=op.f("uq_positions_code")),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("match_minutes", sa.Integer(), server_default="50", nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("name", name=op.f("uq_seasons_name")),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=30), nullable=True),
        sa.Column("colours", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("name", name=op.f("uq_teams_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('coach', 'admin')", name=op.f("ck_users_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "fixtures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("opposition_team_id", sa.Integer(), nullable=False),
        sa.Column("match_number", sa.Integer(), nullable=True),
        sa.Column("kickoff_at", sa.DateTime(), nullable=False),
        sa.Column("venue", sa.String(length=10), nullable=False),
        sa.Column("venue_notes", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("our_score", sa.Integer(), nullable=True),
        sa.Column("their_score", sa.Integer(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'played', 'postponed', 'cancelled', 'abandoned')",
            name=op.f("ck_fixtures_status"),
        ),
        sa.CheckConstraint("venue IN ('home', 'away', 'neutral')", name=op.f("ck_fixtures_venue")),
        sa.CheckConstraint(
            "our_score IS NULL OR our_score >= 0", name=op.f("ck_fixtures_our_score_nonneg")
        ),
        sa.CheckConstraint(
            "their_score IS NULL OR their_score >= 0", name=op.f("ck_fixtures_their_score_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_fixtures_competition_id_competitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opposition_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_opposition_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_fixtures_season_id_seasons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixtures")),
        sa.UniqueConstraint(
            "season_id", "match_number", name=op.f("uq_fixtures_season_id_match_number")
        ),
    )
    with op.batch_alter_table("fixtures", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fixtures_opposition_team_id"), ["opposition_team_id"], unique=False
        )
        batch_op.create_index(
            "ix_fixtures_season_id_kickoff_at", ["season_id", "kickoff_at"], unique=False
        )

    op.create_table(
        "squad_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("squad_number", sa.Integer(), nullable=True),
        sa.Column("primary_position_id", sa.Integer(), nullable=True),
        sa.Column("joined_at", sa.Date(), nullable=True),
        sa.Column("left_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_squad_members_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["primary_position_id"],
            ["positions.id"],
            name=op.f("fk_squad_members_primary_position_id_positions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_squad_members_season_id_seasons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_squad_members")),
        sa.UniqueConstraint(
            "season_id", "player_id", name=op.f("uq_squad_members_season_id_player_id")
        ),
    )
    with op.batch_alter_table("squad_members", schema=None) as batch_op:
        batch_op.create_index(
            "uq_squad_members_season_id_squad_number",
            ["season_id", "squad_number"],
            unique=True,
            sqlite_where=sa.text("squad_number IS NOT NULL"),
        )

    op.create_table(
        "appearances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("started", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column("shirt_number", sa.Integer(), nullable=True),
        sa.Column("captain", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_appearances_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_appearances_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_appearances_position_id_positions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appearances")),
        sa.UniqueConstraint(
            "fixture_id", "player_id", name=op.f("uq_appearances_fixture_id_player_id")
        ),
    )
    with op.batch_alter_table("appearances", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_appearances_player_id"), ["player_id"], unique=False)

    op.create_table(
        "awards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("award_type_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=True),
        sa.Column("period_label", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["award_type_id"],
            ["award_types.id"],
            name=op.f("fk_awards_award_type_id_award_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_awards_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_awards_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_awards_season_id_seasons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_awards")),
        sa.UniqueConstraint(
            "award_type_id",
            "fixture_id",
            "player_id",
            name=op.f("uq_awards_award_type_id_fixture_id_player_id"),
        ),
    )
    with op.batch_alter_table("awards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_awards_player_id"), ["player_id"], unique=False)
        batch_op.create_index(
            "ix_awards_season_id_award_type_id", ["season_id", "award_type_id"], unique=False
        )

    op.create_table(
        "match_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("related_event_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(event_type = 'opp_own_goal' AND player_id IS NULL) OR (event_type <> 'opp_own_goal' AND player_id IS NOT NULL)",
            name=op.f("ck_match_events_player_required"),
        ),
        sa.CheckConstraint(
            "event_type IN ('goal', 'assist', 'own_goal', 'opp_own_goal')",
            name=op.f("ck_match_events_event_type"),
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_match_events_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_match_events_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["related_event_id"],
            ["match_events.id"],
            name=op.f("fk_match_events_related_event_id_match_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_events")),
    )
    with op.batch_alter_table("match_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_match_events_fixture_id_sequence", ["fixture_id", "sequence"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_match_events_player_id"), ["player_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_match_events_related_event_id"), ["related_event_id"], unique=False
        )

    op.create_table(
        "media_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("match_event_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(fixture_id IS NOT NULL) + (player_id IS NOT NULL) + (match_event_id IS NOT NULL) = 1",
            name=op.f("ck_media_links_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_media_links_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["match_event_id"],
            ["match_events.id"],
            name=op.f("fk_media_links_match_event_id_match_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_media_links_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_media_links_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_links")),
        sa.UniqueConstraint(
            "media_id",
            "fixture_id",
            "player_id",
            "match_event_id",
            name=op.f("uq_media_links_media_id_fixture_id_player_id_match_event_id"),
        ),
    )
    with op.batch_alter_table("media_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_media_links_fixture_id"), ["fixture_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_media_links_match_event_id"), ["match_event_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_media_links_media_id"), ["media_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_links_player_id"), ["player_id"], unique=False)

    op.create_table(
        "player_stints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appearance_id", sa.Integer(), nullable=False),
        sa.Column("on_minute", sa.Integer(), nullable=False),
        sa.Column("off_minute", sa.Integer(), nullable=True),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "off_minute IS NULL OR off_minute > on_minute",
            name=op.f("ck_player_stints_off_after_on"),
        ),
        sa.CheckConstraint("on_minute >= 0", name=op.f("ck_player_stints_on_minute_nonneg")),
        sa.ForeignKeyConstraint(
            ["appearance_id"],
            ["appearances.id"],
            name=op.f("fk_player_stints_appearance_id_appearances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_player_stints_position_id_positions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_stints")),
    )
    with op.batch_alter_table("player_stints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_player_stints_appearance_id"), ["appearance_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_stints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_stints_appearance_id"))

    op.drop_table("player_stints")
    with op.batch_alter_table("media_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_links_player_id"))
        batch_op.drop_index(batch_op.f("ix_media_links_media_id"))
        batch_op.drop_index(batch_op.f("ix_media_links_match_event_id"))
        batch_op.drop_index(batch_op.f("ix_media_links_fixture_id"))

    op.drop_table("media_links")
    with op.batch_alter_table("match_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_match_events_related_event_id"))
        batch_op.drop_index(batch_op.f("ix_match_events_player_id"))
        batch_op.drop_index("ix_match_events_fixture_id_sequence")

    op.drop_table("match_events")
    with op.batch_alter_table("awards", schema=None) as batch_op:
        batch_op.drop_index("ix_awards_season_id_award_type_id")
        batch_op.drop_index(batch_op.f("ix_awards_player_id"))

    op.drop_table("awards")
    with op.batch_alter_table("appearances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appearances_player_id"))

    op.drop_table("appearances")
    with op.batch_alter_table("squad_members", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_squad_members_season_id_squad_number",
            sqlite_where=sa.text("squad_number IS NOT NULL"),
        )

    op.drop_table("squad_members")
    with op.batch_alter_table("fixtures", schema=None) as batch_op:
        batch_op.drop_index("ix_fixtures_season_id_kickoff_at")
        batch_op.drop_index(batch_op.f("ix_fixtures_opposition_team_id"))

    op.drop_table("fixtures")
    op.drop_table("users")
    op.drop_table("teams")
    op.drop_table("seasons")
    op.drop_table("positions")
    op.drop_table("players")
    op.drop_table("media")
    op.drop_table("competitions")
    op.drop_table("award_types")
    # ### end Alembic commands ###
