"""selection guests

Revision ID: 013f58ab23ce
Revises: f6564b0195f1
Create Date: 2026-10-03 15:23:28.513301
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "013f58ab23ce"
down_revision: str | None = "f6564b0195f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fixture_selection_guests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_fixture_selection_guests_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["fixture_selections.id"],
            name=op.f("fk_fixture_selection_guests_selection_id_fixture_selections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixture_selection_guests")),
        sa.UniqueConstraint(
            "selection_id",
            "player_id",
            name=op.f("uq_fixture_selection_guests_selection_id_player_id"),
        ),
    )
    with op.batch_alter_table("fixture_selection_guests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fixture_selection_guests_selection_id"), ["selection_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fixture_selection_guests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fixture_selection_guests_selection_id"))

    op.drop_table("fixture_selection_guests")
    # ### end Alembic commands ###
