"""match notes

Revision ID: 80ec87bd57d9
Revises: 06919a849b32
Create Date: 2026-09-15 21:43:24.512909
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "80ec87bd57d9"
down_revision: str | None = "06919a849b32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_match_notes_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_match_notes_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_notes")),
    )
    with op.batch_alter_table("match_notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_match_notes_fixture_id"), ["fixture_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("match_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_match_notes_fixture_id"))

    op.drop_table("match_notes")
    # ### end Alembic commands ###
