"""squad selection

Pre-match squad selection: one fixture_selections row per fixture (coaching on the day,
notes for parents) with fixture_selection_players rows (start / sub / unavailable + reason),
and team_seasons.arrival_lead_minutes for "Please arrive at ...".

Revision ID: 47fa311d91b1
Revises: 3f1c2a9d7b4e
Create Date: 2026-09-20 12:33:00.818352
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "47fa311d91b1"
down_revision: str | None = "3f1c2a9d7b4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fixture_selections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("coaching", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_fixture_selections_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_fixture_selections_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixture_selections")),
        sa.UniqueConstraint("fixture_id", name=op.f("uq_fixture_selections_fixture_id")),
    )
    op.create_table(
        "fixture_selection_players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "status IN ('start', 'sub', 'unavailable')",
            name=op.f("ck_fixture_selection_players_status"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_fixture_selection_players_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["fixture_selections.id"],
            name=op.f("fk_fixture_selection_players_selection_id_fixture_selections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixture_selection_players")),
        sa.UniqueConstraint(
            "selection_id",
            "player_id",
            name=op.f("uq_fixture_selection_players_selection_id_player_id"),
        ),
    )
    with op.batch_alter_table("fixture_selection_players", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fixture_selection_players_selection_id"), ["selection_id"], unique=False
        )

    with op.batch_alter_table("team_seasons", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("arrival_lead_minutes", sa.Integer(), server_default="30", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("team_seasons", schema=None) as batch_op:
        batch_op.drop_column("arrival_lead_minutes")

    with op.batch_alter_table("fixture_selection_players", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fixture_selection_players_selection_id"))

    op.drop_table("fixture_selection_players")
    op.drop_table("fixture_selections")
    # ### end Alembic commands ###
