"""fixture external id

Revision ID: f6564b0195f1
Revises: 47fa311d91b1
Create Date: 2026-09-20 22:08:18.159919
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f6564b0195f1"
down_revision: str | None = "47fa311d91b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fixtures", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_id", sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_fixtures_external_id"), ["external_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fixtures", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_fixtures_external_id"), type_="unique")
        batch_op.drop_column("external_id")

    # ### end Alembic commands ###
