/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/award-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Award Types */
        get: operations["list_award_types_api_v1_award_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Competitions */
        get: operations["list_competitions_api_v1_competitions_get"];
        put?: never;
        /** Create Competition */
        post: operations["create_competition_api_v1_competitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/competitions/{competition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Competition */
        delete: operations["delete_competition_api_v1_competitions__competition_id__delete"];
        options?: never;
        head?: never;
        /** Update Competition */
        patch: operations["update_competition_api_v1_competitions__competition_id__patch"];
        trace?: never;
    };
    "/api/v1/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fixtures */
        get: operations["list_fixtures_api_v1_fixtures_get"];
        put?: never;
        /** Create Fixture */
        post: operations["create_fixture_api_v1_fixtures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fixtures/{fixture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fixture */
        get: operations["get_fixture_api_v1_fixtures__fixture_id__get"];
        put?: never;
        post?: never;
        /** Delete Fixture */
        delete: operations["delete_fixture_api_v1_fixtures__fixture_id__delete"];
        options?: never;
        head?: never;
        /** Update Fixture */
        patch: operations["update_fixture_api_v1_fixtures__fixture_id__patch"];
        trace?: never;
    };
    "/api/v1/fixtures/{fixture_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Submit Result
         * @description Post-match entry: appearances, goals/assists, awards and score in one write.
         */
        put: operations["submit_result_api_v1_fixtures__fixture_id__result_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_api_v1_players_get"];
        put?: never;
        /** Create Player */
        post: operations["create_player_api_v1_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["get_player_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Player */
        patch: operations["update_player_api_v1_players__player_id__patch"];
        trace?: never;
    };
    "/api/v1/players/{player_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Stats */
        get: operations["player_stats_api_v1_players__player_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_api_v1_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_api_v1_seasons_get"];
        put?: never;
        /** Create Season */
        post: operations["create_season_api_v1_seasons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Season */
        get: operations["current_season_api_v1_seasons_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season */
        get: operations["get_season_api_v1_seasons__season_id__get"];
        put?: never;
        post?: never;
        /** Delete Season */
        delete: operations["delete_season_api_v1_seasons__season_id__delete"];
        options?: never;
        head?: never;
        /** Update Season */
        patch: operations["update_season_api_v1_seasons__season_id__patch"];
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/make-current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make Current */
        post: operations["make_current_api_v1_seasons__season_id__make_current_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/squad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Squad */
        get: operations["list_squad_api_v1_seasons__season_id__squad_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/squad/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Squad Member */
        put: operations["upsert_squad_member_api_v1_seasons__season_id__squad__player_id__put"];
        post?: never;
        /** Remove Squad Member */
        delete: operations["remove_squad_member_api_v1_seasons__season_id__squad__player_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/stats/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season Leaderboard */
        get: operations["season_leaderboard_api_v1_seasons__season_id__stats_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season Summary */
        get: operations["season_summary_api_v1_seasons__season_id__stats_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_v1_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_api_v1_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_api_v1_teams__team_id__get"];
        put?: never;
        post?: never;
        /** Delete Team */
        delete: operations["delete_team_api_v1_teams__team_id__delete"];
        options?: never;
        head?: never;
        /** Update Team */
        patch: operations["update_team_api_v1_teams__team_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppearanceInput */
        AppearanceInput: {
            /**
             * Captain
             * @default false
             */
            captain?: boolean;
            /** Player Id */
            player_id: number;
            /** Position Id */
            position_id?: number | null;
            /** Shirt Number */
            shirt_number?: number | null;
            /**
             * Started
             * @default true
             */
            started?: boolean;
        };
        /** AppearanceRead */
        AppearanceRead: {
            /** Captain */
            captain: boolean;
            /** Id */
            id: number;
            player: components["schemas"]["PlayerSummary"];
            position: components["schemas"]["PositionRead"] | null;
            /** Shirt Number */
            shirt_number: number | null;
            /** Started */
            started: boolean;
        };
        /** AwardCount */
        AwardCount: {
            /** Award Type Code */
            award_type_code: string;
            /** Award Type Id */
            award_type_id: number;
            /** Count */
            count: number;
        };
        /** AwardInput */
        AwardInput: {
            /** Award Type Id */
            award_type_id: number;
            /** Player Id */
            player_id: number;
        };
        /** AwardRead */
        AwardRead: {
            award_type: components["schemas"]["AwardTypeRead"];
            /** Fixture Id */
            fixture_id: number | null;
            /** Id */
            id: number;
            /** Notes */
            notes: string | null;
            /** Period Label */
            period_label: string | null;
            player: components["schemas"]["PlayerSummary"];
        };
        /**
         * AwardScope
         * @enum {string}
         */
        AwardScope: "match" | "month" | "season";
        /** AwardTypeRead */
        AwardTypeRead: {
            /** Code */
            code: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            scope: components["schemas"]["AwardScope"];
            /** Sort Order */
            sort_order: number;
        };
        /** CompetitionCreate */
        CompetitionCreate: {
            /**
             * Is Active
             * @default true
             */
            is_active?: boolean;
            /** Name */
            name: string;
            type: components["schemas"]["CompetitionType"];
        };
        /** CompetitionRead */
        CompetitionRead: {
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            type: components["schemas"]["CompetitionType"];
        };
        /**
         * CompetitionType
         * @enum {string}
         */
        CompetitionType: "league" | "cup" | "friendly" | "tournament";
        /** CompetitionUpdate */
        CompetitionUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
            type?: components["schemas"]["CompetitionType"] | null;
        };
        /** FixtureCreate */
        FixtureCreate: {
            /** Competition Id */
            competition_id: number;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            /** Match Number */
            match_number?: number | null;
            /** Notes */
            notes?: string | null;
            /** Opposition Team Id */
            opposition_team_id: number;
            /** Season Id */
            season_id: number;
            /** @default scheduled */
            status?: components["schemas"]["FixtureStatus"];
            /** @default home */
            venue?: components["schemas"]["Venue"];
            /** Venue Notes */
            venue_notes?: string | null;
        };
        /** FixtureDetail */
        FixtureDetail: {
            /** Appearances */
            appearances: components["schemas"]["AppearanceRead"][];
            /** Awards */
            awards: components["schemas"]["AwardRead"][];
            competition: components["schemas"]["CompetitionRead"];
            /** Duration Minutes */
            duration_minutes: number | null;
            /** Goals */
            goals: components["schemas"]["GoalRead"][];
            /** Id */
            id: number;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            /** Match Number */
            match_number: number | null;
            /** Notes */
            notes: string | null;
            opposition: components["schemas"]["TeamRead"];
            /** Our Score */
            our_score: number | null;
            /** Season Id */
            season_id: number;
            status: components["schemas"]["FixtureStatus"];
            /** Their Score */
            their_score: number | null;
            venue: components["schemas"]["Venue"];
            /** Venue Notes */
            venue_notes: string | null;
            /** Warnings */
            warnings: string[];
        };
        /** FixtureRead */
        FixtureRead: {
            competition: components["schemas"]["CompetitionRead"];
            /** Duration Minutes */
            duration_minutes: number | null;
            /** Id */
            id: number;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            /** Match Number */
            match_number: number | null;
            /** Notes */
            notes: string | null;
            opposition: components["schemas"]["TeamRead"];
            /** Our Score */
            our_score: number | null;
            /** Season Id */
            season_id: number;
            status: components["schemas"]["FixtureStatus"];
            /** Their Score */
            their_score: number | null;
            venue: components["schemas"]["Venue"];
            /** Venue Notes */
            venue_notes: string | null;
        };
        /**
         * FixtureStatus
         * @enum {string}
         */
        FixtureStatus: "scheduled" | "played" | "postponed" | "cancelled" | "abandoned";
        /** FixtureUpdate */
        FixtureUpdate: {
            /** Competition Id */
            competition_id?: number | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Kickoff At */
            kickoff_at?: string | null;
            /** Match Number */
            match_number?: number | null;
            /** Notes */
            notes?: string | null;
            /** Opposition Team Id */
            opposition_team_id?: number | null;
            /** Our Score */
            our_score?: number | null;
            status?: components["schemas"]["FixtureStatus"] | null;
            /** Their Score */
            their_score?: number | null;
            venue?: components["schemas"]["Venue"] | null;
            /** Venue Notes */
            venue_notes?: string | null;
        };
        /** FormEntry */
        FormEntry: {
            /** Fixture Id */
            fixture_id: number;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            /** Opposition */
            opposition: string;
            /** Our Score */
            our_score: number;
            /**
             * Result
             * @enum {string}
             */
            result: "W" | "D" | "L";
            /** Their Score */
            their_score: number;
        };
        /**
         * GoalInput
         * @description scorer_id None + event_type opp_own_goal = opposition own goal.
         */
        GoalInput: {
            /** Assisted By Id */
            assisted_by_id?: number | null;
            /**
             * Event Type
             * @default goal
             */
            event_type?: string;
            /** Minute */
            minute?: number | null;
            /** Notes */
            notes?: string | null;
            /** Scorer Id */
            scorer_id?: number | null;
        };
        /**
         * GoalRead
         * @description A goal event with its assist folded in - the shape the UI wants.
         */
        GoalRead: {
            /** Assist Event Id */
            assist_event_id: number | null;
            assisted_by: components["schemas"]["PlayerSummary"] | null;
            /** Event Type */
            event_type: string;
            /** Id */
            id: number;
            /** Minute */
            minute: number | null;
            /** Notes */
            notes: string | null;
            scorer: components["schemas"]["PlayerSummary"] | null;
            /** Sequence */
            sequence: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HighlightTile */
        HighlightTile: {
            /** Label */
            label: string;
            /** Players */
            players: components["schemas"]["PlayerSummary"][];
            /** Value */
            value: number;
        };
        /** Leaderboard */
        Leaderboard: {
            /** Award Types */
            award_types: components["schemas"]["AwardCount"][];
            /** Competition Type */
            competition_type: string | null;
            /** Rows */
            rows: components["schemas"]["PlayerStatsRow"][];
            /** Season Id */
            season_id: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** PlayerCreate */
        PlayerCreate: {
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** First Name */
            first_name: string;
            /** Joined Date */
            joined_date?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Season Id */
            season_id?: number | null;
            /** Squad Number */
            squad_number?: number | null;
        };
        /** PlayerRead */
        PlayerRead: {
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Display Name */
            display_name: string;
            /** First Name */
            first_name: string;
            /** Id */
            id: number;
            /** Joined Date */
            joined_date: string | null;
            /** Last Name */
            last_name: string | null;
            /** Left Date */
            left_date: string | null;
            /** Notes */
            notes: string | null;
        };
        /** PlayerStatsRow */
        PlayerStatsRow: {
            /** Appearances */
            appearances: number;
            /** Assists */
            assists: number;
            /** Awards */
            awards: components["schemas"]["AwardCount"][];
            /** Goals */
            goals: number;
            /** Goals Per Game */
            goals_per_game: number;
            /** Minutes */
            minutes: number | null;
            /** Own Goals */
            own_goals: number;
            player: components["schemas"]["PlayerSummary"];
            /** Squad Number */
            squad_number: number | null;
            /** Starts */
            starts: number;
        };
        /**
         * PlayerSummary
         * @description Lightweight embed for nested responses.
         */
        PlayerSummary: {
            /** Display Name */
            display_name: string;
            /** Id */
            id: number;
        };
        /** PlayerUpdate */
        PlayerUpdate: {
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Joined Date */
            joined_date?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Left Date */
            left_date?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * PositionCategory
         * @enum {string}
         */
        PositionCategory: "GK" | "DEF" | "MID" | "FWD";
        /** PositionRead */
        PositionRead: {
            category: components["schemas"]["PositionCategory"];
            /** Code */
            code: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Sort Order */
            sort_order: number;
        };
        /**
         * ResultSubmit
         * @description The whole result of a match in one transactional write.
         */
        ResultSubmit: {
            /** Appearances */
            appearances: components["schemas"]["AppearanceInput"][];
            /**
             * Awards
             * @default []
             */
            awards?: components["schemas"]["AwardInput"][];
            /**
             * Goals
             * @default []
             */
            goals?: components["schemas"]["GoalInput"][];
            /** Our Score */
            our_score: number;
            /** Their Score */
            their_score: number;
        };
        /** SeasonCreate */
        SeasonCreate: {
            /** End Date */
            end_date?: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current?: boolean;
            /**
             * Match Minutes
             * @default 50
             */
            match_minutes?: number;
            /**
             * Name
             * @example 2026/27
             */
            name: string;
            /** Start Date */
            start_date?: string | null;
        };
        /** SeasonRead */
        SeasonRead: {
            /** End Date */
            end_date: string | null;
            /** Id */
            id: number;
            /** Is Current */
            is_current: boolean;
            /** Match Minutes */
            match_minutes: number;
            /** Name */
            name: string;
            /** Start Date */
            start_date: string | null;
        };
        /** SeasonSummary */
        SeasonSummary: {
            /** Form */
            form: components["schemas"]["FormEntry"][];
            /** Highlights */
            highlights: components["schemas"]["HighlightTile"][];
            league: components["schemas"]["TeamRecord"];
            overall: components["schemas"]["TeamRecord"];
            /** Season Id */
            season_id: number;
        };
        /** SeasonUpdate */
        SeasonUpdate: {
            /** End Date */
            end_date?: string | null;
            /** Match Minutes */
            match_minutes?: number | null;
            /** Name */
            name?: string | null;
            /** Start Date */
            start_date?: string | null;
        };
        /** SquadMemberRead */
        SquadMemberRead: {
            /** Id */
            id: number;
            /** Joined At */
            joined_at: string | null;
            /** Left At */
            left_at: string | null;
            player: components["schemas"]["PlayerRead"];
            primary_position: components["schemas"]["PositionRead"] | null;
            /** Season Id */
            season_id: number;
            /** Squad Number */
            squad_number: number | null;
        };
        /** SquadMemberUpsert */
        SquadMemberUpsert: {
            /** Joined At */
            joined_at?: string | null;
            /** Left At */
            left_at?: string | null;
            /** Primary Position Id */
            primary_position_id?: number | null;
            /** Squad Number */
            squad_number?: number | null;
        };
        /** TeamCreate */
        TeamCreate: {
            /** Colours */
            colours?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Short Name */
            short_name?: string | null;
        };
        /** TeamRead */
        TeamRead: {
            /** Colours */
            colours: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Short Name */
            short_name: string | null;
        };
        /** TeamRecord */
        TeamRecord: {
            /** Drawn */
            drawn: number;
            /** Goal Difference */
            goal_difference: number;
            /** Goals Against */
            goals_against: number;
            /** Goals For */
            goals_for: number;
            /** Lost */
            lost: number;
            /** Played */
            played: number;
            /** Win Pct */
            win_pct: number;
            /** Won */
            won: number;
        };
        /** TeamUpdate */
        TeamUpdate: {
            /** Colours */
            colours?: string | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Short Name */
            short_name?: string | null;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            role: components["schemas"]["UserRole"];
            /** Username */
            username: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "coach" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Venue
         * @enum {string}
         */
        Venue: "home" | "away" | "neutral";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_award_types_api_v1_award_types_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwardTypeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_competitions_api_v1_competitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_competition_api_v1_competitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_competition_api_v1_competitions__competition_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competition_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_competition_api_v1_competitions__competition_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competition_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fixtures_api_v1_fixtures_get: {
        parameters: {
            query?: {
                season_id?: number | null;
                competition_id?: number | null;
                status?: components["schemas"]["FixtureStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fixture_api_v1_fixtures_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixtureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fixture_api_v1_fixtures__fixture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixture_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fixture_api_v1_fixtures__fixture_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixture_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fixture_api_v1_fixtures__fixture_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixture_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixtureUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_result_api_v1_fixtures__fixture_id__result_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixture_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_api_v1_players_get: {
        parameters: {
            query?: {
                include_left?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_player_api_v1_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_api_v1_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_api_v1_players__player_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_stats_api_v1_players__player_id__stats_get: {
        parameters: {
            query?: {
                season_id?: number | null;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStatsRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_seasons_api_v1_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_season_api_v1_seasons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_season_api_v1_seasons_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_season_api_v1_seasons__season_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_season_api_v1_seasons__season_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_season_api_v1_seasons__season_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    make_current_api_v1_seasons__season_id__make_current_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_squad_api_v1_seasons__season_id__squad_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadMemberRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_squad_member_api_v1_seasons__season_id__squad__player_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
                player_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SquadMemberUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadMemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_squad_member_api_v1_seasons__season_id__squad__player_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
                player_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    season_leaderboard_api_v1_seasons__season_id__stats_leaderboard_get: {
        parameters: {
            query?: {
                competition_type?: string | null;
            };
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    season_summary_api_v1_seasons__season_id__stats_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_team_api_v1_teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_api_v1_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_team_api_v1_teams__team_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_api_v1_teams__team_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: {
                abgfc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
